import AsyncStorage from "@react-native-async-storage/async-storage";
import { useCallback, useEffect, useState } from "react";
import { FlatList, Pressable, ScrollView, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { api } from "../../src/api";
import { useApp } from "../../src/app-state";
import { t } from "../../src/i18n";
import { readRecentlyViewed } from "../../src/commerce";
import type { Category, Product, ProductPreview } from "../../src/types";
import { Header, ProductCard, Screen, styles } from "../../src/ui";
import { colors, space } from "../../src/theme";

export default function HomeScreen() {
  const { locale, setLocale } = useApp(); const copy = t(locale); const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [recent, setRecent] = useState<ProductPreview[]>([]);
  useEffect(() => { Promise.all([api.products(`locale=${locale}`), api.categories(locale)]).then(([items, nextCategories]) => { setProducts(items.slice(0, 8)); setCategories(nextCategories); }).catch(() => undefined); }, [locale]);
  useFocusEffect(useCallback(() => { AsyncStorage.getItem("recentProducts").then((raw) => setRecent(readRecentlyViewed(raw ? JSON.parse(raw) : []))).catch(() => setRecent([])); }, []));
  return <Screen><Header title="Zambiel" right={<Pressable accessibilityRole="button" accessibilityLabel="Change language" onPress={() => setLocale(locale === "de" ? "en" : "de")} style={{ minWidth: 48, minHeight: 48, alignItems: "center", justifyContent: "center" }}><Text style={{ fontFamily: "Inter_600SemiBold", color: colors.primary }}>{locale.toUpperCase()}</Text></Pressable>}/><FlatList data={products} numColumns={2} keyExtractor={(item) => item.id} columnWrapperStyle={{ gap: space.sm }} contentContainerStyle={{ padding: space.md, gap: space.sm, paddingBottom: space.xl }} ListHeaderComponent={<View style={{ gap: space.lg, marginBottom: space.lg }}><View style={{ backgroundColor: colors.primary, borderRadius: 20, padding: space.lg, borderBottomWidth: 4, borderBottomColor: colors.accent }}><Text style={{ fontFamily: "Archivo_700Bold", fontSize: 30, lineHeight: 36, color: colors.surface }}>{locale === "de" ? "Für deinen Alltag. Aus der Schweiz." : "For everyday life. From Switzerland."}</Text></View><View><Text style={styles.title}>{copy.categories}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: space.sm, paddingTop: 12 }}>{categories.map((category) => <Pressable key={category.id} onPress={() => router.push({ pathname: "/(tabs)/shop", params: { category: category.slug } })} style={({ pressed }) => ({ minHeight: 48, justifyContent: "center", paddingHorizontal: 16, borderRadius: 24, backgroundColor: pressed ? colors.border : colors.surface, borderWidth: 1, borderColor: colors.border })}><Text style={{ color: colors.text, fontFamily: "Inter_600SemiBold" }}>{category.name}</Text></Pressable>)}</ScrollView></View>{recent.length ? <View><Text style={styles.title}>{locale === "de" ? "Zuletzt angesehen" : "Recently viewed"}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: space.sm, paddingTop: 12 }}>{recent.map((product) => <ProductCard key={product.id} product={product} style={{ width: 180 }} onPress={() => router.push(`/product/${product.slug}`)}/>)}</ScrollView></View> : null}<Text style={styles.title}>{copy.featured}</Text></View>} renderItem={({ item }) => <ProductCard product={item} onPress={() => router.push(`/product/${item.slug}`)}/>} /></Screen>;
}
