ALTER TABLE `order` MODIFY `paymentMethod` ENUM('STRIPE', 'CASH_ON_DELIVERY', 'PAY_AT_PICKUP', 'INVOICE_BANK_TRANSFER') NOT NULL;
ALTER TABLE `payment` MODIFY `provider` ENUM('STRIPE', 'CASH', 'INVOICE_BANK_TRANSFER') NOT NULL;
ALTER TABLE `payment` MODIFY `status` ENUM('PENDING', 'PENDING_VERIFICATION', 'PAID', 'FAILED', 'PARTIALLY_REFUNDED', 'REFUNDED') NOT NULL DEFAULT 'PENDING';
