import { Image, Pressable, StyleSheet, Text, TextInput, View, type PressableProps, type TextInputProps } from "react-native";
import type { PropsWithChildren, ReactNode } from "react";
import { colors, space } from "./theme";
import { money } from "./commerce";
import { useApp } from "./app-state";
import type { Product } from "./types";

export function Screen({ children }: PropsWithChildren) { return <View style={s.screen}>{children}</View>; }
export function Header({ title, right }: { title: string; right?: ReactNode }) { return <View style={s.header}><Text accessibilityRole="header" style={s.title}>{title}</Text>{right}</View>; }
export function Button({ children, kind = "primary", ...props }: PropsWithChildren<PressableProps & { kind?: "primary" | "secondary" | "danger" }>) { return <Pressable accessibilityRole="button" android_ripple={{ color: "#FFFFFF22" }} style={({ pressed }) => [s.button, kind === "secondary" && s.buttonSecondary, kind === "danger" && s.buttonDanger, pressed && s.pressed, props.disabled && s.disabled]} {...props}><Text style={[s.buttonText, kind === "secondary" && s.buttonSecondaryText]}>{children}</Text></Pressable>; }
export function Field({ label, error, ...props }: TextInputProps & { label: string; error?: string }) { return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} accessibilityHint={error} style={[s.input, error && s.inputError]} placeholderTextColor={colors.muted} {...props}/>{error ? <Text accessibilityRole="alert" style={s.error}>{error}</Text> : null}</View>; }
export function Empty({ children }: PropsWithChildren) { return <View style={s.empty}><Text style={s.emptyText}>{children}</Text></View>; }
export function ProductCard({ product, onPress }: { product: Product; onPress: () => void }) { const { locale } = useApp(); return <Pressable accessibilityRole="button" accessibilityLabel={`${product.name}, ${money(product.minimumPriceRappen, locale)}`} onPress={onPress} style={({ pressed }) => [s.card, pressed && s.pressed]}>{product.imageUrl ? <Image source={{ uri: product.imageUrl }} style={s.productImage} accessibilityLabel={product.name}/> : <View style={[s.productImage, s.placeholder]}/>}<View style={s.cardBody}><Text numberOfLines={2} style={s.productName}>{product.name}</Text><Text style={s.price}>{money(product.minimumPriceRappen, locale)}</Text></View></Pressable>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, header: { minHeight: 64, paddingHorizontal: space.md, paddingVertical: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border }, title: { fontFamily: "Archivo_700Bold", fontSize: 25, color: colors.primary }, button: { minHeight: 48, borderRadius: 12, paddingHorizontal: 18, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary }, buttonSecondary: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.primary }, buttonDanger: { backgroundColor: colors.danger, marginTop: space.lg }, buttonText: { fontFamily: "Inter_600SemiBold", color: colors.surface, fontSize: 16 }, buttonSecondaryText: { color: colors.primary }, pressed: { opacity: .72 }, disabled: { opacity: .45 }, field: { gap: 6 }, label: { color: colors.text, fontFamily: "Inter_600SemiBold", fontSize: 14 }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 12, paddingHorizontal: 14, color: colors.text, fontFamily: "Inter_400Regular", fontSize: 16 }, inputError: { borderColor: colors.danger }, error: { color: colors.danger, fontSize: 13 }, empty: { padding: 32, alignItems: "center" }, emptyText: { color: colors.muted, fontSize: 16, textAlign: "center" }, card: { width: "48%", borderRadius: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, overflow: "hidden" }, productImage: { width: "100%", aspectRatio: 1, backgroundColor: "#E8ECE9" }, placeholder: { borderBottomWidth: 1, borderColor: colors.border }, cardBody: { padding: 12, gap: 6 }, productName: { minHeight: 42, color: colors.text, fontFamily: "Inter_600SemiBold", fontSize: 15, lineHeight: 21 }, price: { color: colors.primary, fontFamily: "Archivo_700Bold", fontSize: 16 } });
export const styles = s;
