import { adminAction } from "@/app/admin/(protected)/actions";
import { AdminFormDialog } from "@/components/admin/admin-form-dialog";
import { AdminPage, Check, Field, Notice, SaveBar } from "@/components/admin/admin-ui";
import { siteConfig } from "@/config/site";
import { formatMoney, formatMoneyInput } from "@/lib/orders";
import { getSettingsAdminData } from "@/server/services/admin";

type Zone = Awaited<ReturnType<typeof getSettingsAdminData>>["zones"][number];

export default async function ZonesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ zones }, feedback] = await Promise.all([getSettingsAdminData(), searchParams]);
  const returnTo = "/admin/settings/delivery-zones";
  return <AdminPage title="Shipping countries" description="Country-specific CHF fees, order minimums, and free-shipping thresholds." actions={<AdminFormDialog trigger="Add country" title="Add shipping country" description="Configure shipping for one destination country." variant="primary"><ZoneForm returnTo={returnTo} /></AdminFormDialog>}><Notice {...feedback} /><div className="space-y-4">{zones.length === 0 ? <p className="rounded-xl border bg-white p-8 text-center text-sm text-muted">No shipping countries.</p> : zones.map((zone) => <section key={zone.id} className="overflow-hidden rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold">{zone.nameEn} {zone.countryCode ? <span className="text-muted">({zone.countryCode})</span> : <span className="text-destructive">(country code required)</span>}</h2><p className="text-xs text-muted">{formatMoney(zone.feeRappen, "en")} fee · {formatMoney(zone.minimumSubtotalRappen, "en")} minimum{zone.freeDeliveryThresholdRappen === null ? "" : ` · free from ${formatMoney(zone.freeDeliveryThresholdRappen, "en")}`}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${zone.active && zone.countryCode ? "bg-emerald-50 text-emerald-800" : "bg-background text-muted"}`}>{zone.active && zone.countryCode ? "Active" : "Inactive"}</span><AdminFormDialog trigger="Edit" title={`Edit ${zone.nameEn}`} description="Update country shipping pricing."><ZoneForm returnTo={returnTo} zone={zone} /></AdminFormDialog></div></div></section>)}</div></AdminPage>;
}

function ZoneForm({ returnTo, zone }: { returnTo: string; zone?: Zone }) { return <form action={adminAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="intent" value="zone" />{zone && <input type="hidden" name="id" value={zone.id} />}<Field label="Country code" name="countryCode" maxLength={2} defaultValue={zone?.countryCode ?? ""} required /><Field label="Sort" name="sortOrder" type="number" min="0" defaultValue={zone?.sortOrder ?? 0} required /><Field label="German country name" name="nameDe" defaultValue={zone?.nameDe} required /><Field label="English country name" name="nameEn" defaultValue={zone?.nameEn} required /><Field label={`Shipping fee (${siteConfig.currency})`} name="feeRappen" type="number" min="0" step="0.01" defaultValue={zone ? formatMoneyInput(zone.feeRappen) : ""} required /><Field label={`Minimum order (${siteConfig.currency})`} name="minimumSubtotalRappen" type="number" min="0" step="0.01" defaultValue={zone ? formatMoneyInput(zone.minimumSubtotalRappen) : "0.00"} required /><Field label={`Free-shipping threshold (${siteConfig.currency})`} name="freeDeliveryThresholdRappen" type="number" min="0" step="0.01" defaultValue={zone?.freeDeliveryThresholdRappen == null ? "" : formatMoneyInput(zone.freeDeliveryThresholdRappen)} /><input type="hidden" name="estimatedMinutes" value={zone?.estimatedMinutes ?? 1440} /><Check label="Active" name="active" defaultChecked={zone?.active ?? true} /><div className="sm:col-span-2"><SaveBar returnTo={returnTo} label={zone ? "Save country" : "Add country"} /></div></form>; }
