import Link from "next/link";
import { AdminPage, Empty, Notice } from "@/components/admin/admin-ui";
import { prisma } from "@/server/db";

function storeMode(value?: string) { return value === "b2b" || value === "all" ? value : "b2c"; }

export default async function CategoriesPage({ searchParams }: { searchParams: Promise<{ saved?: string; deleted?: string; q?: string; storeMode?: string }> }) {
  const feedback = await searchParams;
  const mode = storeMode(feedback.storeMode);
  const categories = await prisma.category.findMany({ where: { deletedAt: null, ...(mode === "all" ? {} : { is_b2b: mode === "b2b" }), ...(feedback.q ? { OR: [{ nameEn: { contains: feedback.q } }, { nameDe: { contains: feedback.q } }, { slug: { contains: feedback.q } }] } : {}) }, select: { id: true, slug: true, nameEn: true, active: true, is_b2b: true, parent: { select: { nameEn: true } }, _count: { select: { products: { where: { deletedAt: null } }, children: { where: { deletedAt: null } } } } }, orderBy: [{ sortOrder: "asc" }, { nameEn: "asc" }] });
  return <AdminPage title="Categories" description="Manage storefront categories and subcategories." actions={<Link href="/admin/categories/new" className="inline-flex min-h-11 items-center rounded-lg bg-primary px-5 text-sm font-bold text-white">Add category</Link>}><Notice saved={feedback.saved} deleted={feedback.deleted} /><form className="mb-5 grid gap-3 sm:grid-cols-[1fr_10rem_auto]"><input name="q" defaultValue={feedback.q} placeholder="Name or slug" className="min-h-11 rounded-lg border bg-white px-3" /><select name="storeMode" defaultValue={mode} aria-label="Store mode" className="min-h-11 rounded-lg border bg-white px-3"><option value="b2c">B2C</option><option value="b2b">B2B</option><option value="all">All</option></select><button className="min-h-11 rounded-lg border bg-white px-5 font-bold">Filter</button></form>{categories.length === 0 ? <Empty>No categories match this view.</Empty> : <div className="grid gap-3">{categories.map((category) => <Link key={category.id} href={`/admin/categories/${category.id}`} className="flex min-h-16 items-center justify-between rounded-xl border bg-white p-4 hover:border-primary"><div><strong>{category.parent ? `${category.parent.nameEn} / ` : ""}{category.nameEn}</strong><p className="text-xs text-muted">/{category.slug} · {category.active ? "Active" : "Hidden"} · {category.is_b2b ? "B2B" : "B2C"}</p></div><span className="text-sm text-muted">{category._count.products} products · {category._count.children} children</span></Link>)}</div>}</AdminPage>;
}
