ALTER TABLE `category` ADD COLUMN `is_b2b` BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE `product` ADD COLUMN `is_b2b` BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE `user`
  ADD COLUMN `is_b2b_authorized` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `b2b_status` VARCHAR(32) NOT NULL DEFAULT 'NONE';
