import Link from "next/link";
import { AdminPage, Empty, Notice } from "@/components/admin/admin-ui";
import { prisma } from "@/server/db";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ saved?: string; q?: string; status?: "DRAFT" | "ACTIVE" | "ARCHIVED" }> }) {
  const filters = await searchParams;
  const products = await prisma.product.findMany({ where: { ...(filters.status ? { status: filters.status } : {}), ...(filters.q ? { OR: [{ nameEn: { contains: filters.q } }, { nameDe: { contains: filters.q } }, { variants: { some: { sku: { contains: filters.q } } } }] } : {}) }, include: { category: true, variants: { select: { stockOnHand: true, stockReserved: true, lowStockThreshold: true } } }, orderBy: [{ updatedAt: "desc" }], take: 200 });
  return <AdminPage title="Products" description="Catalog publication, variants, pricing, and stock." actions={<Link href="/admin/products/new" className="inline-flex min-h-11 items-center rounded-lg bg-primary px-5 text-sm font-bold text-white">Add product</Link>}><Notice saved={filters.saved} /><form className="mb-5 grid gap-3 sm:grid-cols-[1fr_12rem_auto]"><input name="q" defaultValue={filters.q} placeholder="Name or SKU" className="min-h-11 rounded-lg border bg-white px-3" /><select name="status" defaultValue={filters.status ?? ""} className="min-h-11 rounded-lg border bg-white px-3"><option value="">All states</option><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option></select><button className="min-h-11 rounded-lg border bg-white px-5 font-bold">Filter</button></form>
    {products.length === 0 ? <Empty>No products match this view.</Empty> : <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-[#F6F6F7] text-xs uppercase text-muted"><tr><th className="p-4">Product</th><th className="p-4">Category</th><th className="p-4">State</th><th className="p-4">Variants</th><th className="p-4">Available stock</th><th className="p-4"><span className="sr-only">Edit</span></th></tr></thead><tbody className="divide-y">{products.map((product) => <tr key={product.id}><td className="p-4"><strong>{product.nameEn}</strong><div className="text-xs text-muted">/{product.slug}</div></td><td className="p-4">{product.category.nameEn}</td><td className="p-4">{product.status}</td><td className="p-4">{product.variants.length}</td><td className="p-4">{product.variants.reduce((sum, variant) => sum + Math.max(0, variant.stockOnHand - variant.stockReserved), 0)}</td><td className="p-4 text-right"><Link href={`/admin/products/${product.id}`} className="font-bold text-primary hover:underline">Edit</Link></td></tr>)}</tbody></table></div>}
  </AdminPage>;
}
